.PHONY: clean All

All:
	@echo "----------Building project:[ abclient - Release ]----------"
	@"$(MAKE)" -f  "abclient.mk"
clean:
	@echo "----------Cleaning project:[ abclient - Release ]----------"
	@"$(MAKE)" -f  "abclient.mk" clean
