#pragma once

#include "Config.h"

using namespace Urho3D;

/// User defined events
namespace AbEvents
{

URHO3D_EVENT(E_SCREENSHOTTAKEN, ScreenshotTaken)
{
    URHO3D_PARAM(P_FILENAME, Filename);        // String
}

URHO3D_EVENT(E_SERVERJOINED, ServerJoined)
{
    URHO3D_PARAM(P_SERVERID, ServerId);        // String
}

URHO3D_EVENT(E_SERVERLEFT, ServerLeft)
{
    URHO3D_PARAM(P_SERVERID, ServerId);        // String
}

URHO3D_EVENT(E_GOTSERVICES, GotServices)
{
}

URHO3D_EVENT(E_SETLEVEL, SetLevel)
{
    URHO3D_PARAM(P_UPDATETICK, UpdateTick);
    URHO3D_PARAM(P_NAME, Name);        // String
    URHO3D_PARAM(P_MAPUUID, MapUuid);            // String
}

URHO3D_EVENT(E_LEVELREADY, LevelReady)
{
    URHO3D_PARAM(P_NAME, Name);        // String
}

URHO3D_EVENT(E_OBJECTSPAWN, ObjectSpawn)
{
    URHO3D_PARAM(P_UPDATETICK, UpdateTick);
    URHO3D_PARAM(P_EXISTING, Existing);      // bool
    URHO3D_PARAM(P_OBJECTID, ObjectId);
    URHO3D_PARAM(P_POSITION, Position);
    URHO3D_PARAM(P_ROTATION, Rotation);
    URHO3D_PARAM(P_SCALE, Scale);
    URHO3D_PARAM(P_STATE, State);            // AB::GameProtocol::CreatureState
    URHO3D_PARAM(P_SPEEDFACTOR, SpeedFactor);  // float
    URHO3D_PARAM(P_DATA, Data);
}

URHO3D_EVENT(E_OBJECTDESPAWN, ObjectDespawn)
{
    URHO3D_PARAM(P_UPDATETICK, UpdateTick);
    URHO3D_PARAM(P_OBJECTID, ObjectId);
}

URHO3D_EVENT(E_OBJECTPOSUPDATE, ObjectPosUpdate)
{
    URHO3D_PARAM(P_UPDATETICK, UpdateTick);
    URHO3D_PARAM(P_OBJECTID, ObjectId);
    URHO3D_PARAM(P_POSITION, Position);
}

URHO3D_EVENT(E_OBJECTROTUPDATE, ObjectRotUpdate)
{
    URHO3D_PARAM(P_UPDATETICK, UpdateTick);
    URHO3D_PARAM(P_OBJECTID, ObjectId);
    URHO3D_PARAM(P_ROTATION, Rotation);
    URHO3D_PARAM(P_MANUAL, Manual);
}

URHO3D_EVENT(E_OBJECTSTATEUPDATE, ObjectStateUpdate)
{
    URHO3D_PARAM(P_UPDATETICK, UpdateTick);
    URHO3D_PARAM(P_OBJECTID, ObjectId);
    URHO3D_PARAM(P_STATE, State);
}

URHO3D_EVENT(E_OBJECTSPEEDUPDATE, ObjectSpeedUpdate)
{
    URHO3D_PARAM(P_UPDATETICK, UpdateTick);
    URHO3D_PARAM(P_OBJECTID, ObjectId);
    URHO3D_PARAM(P_SPEEDFACTOR, SpeedFactor);      // float
}

URHO3D_EVENT(E_OBJECTSELECTED, ObjectSelected)
{
    URHO3D_PARAM(P_UPDATETICK, UpdateTick);
    URHO3D_PARAM(P_SOURCEID, SourceId);
    URHO3D_PARAM(P_TARGETID, TargetId);
}

URHO3D_EVENT(E_SERVERMESSAGE, ServerMessage)
{
    URHO3D_PARAM(P_UPDATETICK, UpdateTick);
    URHO3D_PARAM(P_MESSAGETYPE, MessageType);
    URHO3D_PARAM(P_SENDER, Sender);
    URHO3D_PARAM(P_DATA, Data);
}

URHO3D_EVENT(E_CHATMESSAGE, ChatMessage)
{
    URHO3D_PARAM(P_UPDATETICK, UpdateTick);
    URHO3D_PARAM(P_MESSAGETYPE, MessageType);
    URHO3D_PARAM(P_SENDERID, SenderId);
    URHO3D_PARAM(P_SENDER, Sender);
    URHO3D_PARAM(P_DATA, Data);
}

URHO3D_EVENT(E_MAILINBOX, MailInbox)
{
}

URHO3D_EVENT(E_MAILREAD, MailRead)
{
}

URHO3D_EVENT(E_PARTYINVITED, PartyInvited)
{
    URHO3D_PARAM(P_UPDATETICK, UpdateTick);
    URHO3D_PARAM(P_SOURCEID, SourceId);     // unit32_t
    URHO3D_PARAM(P_TARGETID, TargetId);     // unit32_t
}

URHO3D_EVENT(E_PARTYREMOVED, PartyRemoved)
{
    URHO3D_PARAM(P_UPDATETICK, UpdateTick);
    URHO3D_PARAM(P_SOURCEID, SourceId);     // unit32_t
    URHO3D_PARAM(P_TARGETID, TargetId);     // unit32_t
}

URHO3D_EVENT(E_PARTYADDED, PartyAdded)
{
    URHO3D_PARAM(P_UPDATETICK, UpdateTick);
    URHO3D_PARAM(P_SOURCEID, SourceId);     // unit32_t
    URHO3D_PARAM(P_TARGETID, TargetId);     // unit32_t
}

URHO3D_EVENT(E_PARTYINVITEREMOVED, PartyInviteRemoved)
{
    URHO3D_PARAM(P_UPDATETICK, UpdateTick);
    URHO3D_PARAM(P_SOURCEID, SourceId);     // unit32_t
    URHO3D_PARAM(P_TARGETID, TargetId);     // unit32_t
}

URHO3D_EVENT(E_NEWMAIL , NewMail)
{
    URHO3D_PARAM(P_COUNT, Count);           // int
}

URHO3D_EVENT(E_ACTORNAMECLICKED, ActorNameClicked)
{
    URHO3D_PARAM(P_SOURCEID, SourceId);     // unit32_t
}

// Shortcuts
URHO3D_EVENT(E_SC_TOGGLEMAP, ToggleMap)
{
}

URHO3D_EVENT(E_SC_MOVEFORWARD, MoveForward)
{
}

URHO3D_EVENT(E_SC_MOVEBACKWARD, MoveBackward)
{
}

URHO3D_EVENT(E_SC_MOVELEFT, MoveLeft)
{
}

URHO3D_EVENT(E_SC_MOVERIGHT, MoveRight)
{
}

URHO3D_EVENT(E_SC_TURNLEFT, TurnLeft)
{
}

URHO3D_EVENT(E_SC_TURNRIGHT, TurnRight)
{
}

URHO3D_EVENT(E_SC_KEEPRUNNING, KeepRunning)
{
}

URHO3D_EVENT(E_SC_REVERSECAMERA, ReverseCamera)
{
}

URHO3D_EVENT(E_SC_HIGHLIGHTOBJECTS, HighlightObjects)
{
}

URHO3D_EVENT(E_SC_MOUSELOOK, MouseLook)
{
}

URHO3D_EVENT(E_SC_TOGGLEPARTYWINDOW, TogglePartyWindow)
{
}

URHO3D_EVENT(E_SC_DEFAULTACTION, DefaultAction)
{
}

URHO3D_EVENT(E_SC_TAKESCREENSHOT, TakeScreenshot)
{
}

URHO3D_EVENT(E_SC_TOGGLEMAILWINDOW, ToggleMailWindow)
{
}

URHO3D_EVENT(E_SC_TOGGLENEWMAILWINDOW, ToggleNewMailWindow)
{
}

URHO3D_EVENT(E_SC_TOGGLEMISSIONMAPWINDOW, ToggleMissionMapWindow)
{
}

URHO3D_EVENT(E_SC_REPLYMAIL, ReplyMail)
{
    URHO3D_PARAM(P_RECIPIENT, Recipient);     // String
    URHO3D_PARAM(P_SUBJECT, Subject);         // String
}

URHO3D_EVENT(E_SC_LOGOUT, Logout)
{
}

URHO3D_EVENT(E_SC_SELECTCHARACTER, SelectCharacter)
{
}

URHO3D_EVENT(E_SC_TOGGLEOPTIONS, ToggleOptions)
{
}

URHO3D_EVENT(E_SC_EXITPROGRAM, ExitProgram)
{
}

URHO3D_EVENT(E_SC_CHATGENERAL, ChatGeneral)
{
}

URHO3D_EVENT(E_SC_CHATGUILD, ChatGuild)
{
}

URHO3D_EVENT(E_SC_CHATPARTY, ChatParty)
{
}

URHO3D_EVENT(E_SC_CHATTRADE, ChatTrade)
{
}

URHO3D_EVENT(E_SC_CHATWHISPER, ChatWhisper)
{
}

URHO3D_EVENT(E_SC_TOGGLECHATWINDOW, ToggleChatWindow)
{
}

URHO3D_EVENT(E_SC_HIDEUI, HideUI)
{
}

URHO3D_EVENT(E_SC_SELECTSELF, SelectSelf)
{
}

URHO3D_EVENT(E_SC_SELECTNEXTFOE, SelectNextFoe)
{
}

URHO3D_EVENT(E_SC_SELECTPREVFOE, SelectPrevFoe)
{
}

URHO3D_EVENT(E_SC_SELECTNEXTALLY, SelectNextAlly)
{
}

URHO3D_EVENT(E_SC_SELECTPREVALLY, SelectPrevAlly)
{
}

#ifdef DEBUG_HUD
URHO3D_EVENT(E_SC_TOGGLEDEBUGHUD, ToggleDebugHUD)
{
}

URHO3D_EVENT(E_SC_TOGGLECONSOLE, ToggleConsole)
{
}
#endif

}
