.PHONY: clean all

all:
	@"$(MAKE)" -f  "../makefiles/abscommon.make"
	@"$(MAKE)" -f  "../makefiles/absmath.make"
	@"$(MAKE)" -f  "../makefiles/abstests.make"
clean:
	@"$(MAKE)" -f  "../makefiles/abcommon.make" clean
	@"$(MAKE)" -f  "../makefiles/absmath.make" clean
	@"$(MAKE)" -f  "../makefiles/abstestsd.make" clean
