# GNU Make project makefile autogenerated by Premake

.PHONY: clean prebuild prelink

CC = clang
CXX = clang++
AR = ar r
TARGETDIR = ../Bin
TARGET = $(TARGETDIR)/abdata
OBJDIR = obj/x64/Release/abdata
DEFINES += -DNDEBUG -D_CONSOLE
INCLUDES += -I.. -I../abscommon/abscommon -I../abdb/abdb -I../Include
ALL_CPPFLAGS += $(CPPFLAGS) $(DEFINES) $(INCLUDES)
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O3 -Wall
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS)  -m64 -O3 -Wall -std=c++14
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS += -lpthread -luuid -llua5.3 -labcrypto -lsqlite3 -ldl -lpq -lldap -lssl -lcrypto -lmariadbclient -lz -lgssapi_krb5 -labscommon -labdb
ALL_LDFLAGS += $(LDFLAGS) -L../Lib -L../Lib/x64/Release -L/usr/lib -m64
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS) -v
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef
all: prebuild prelink $(TARGET)
@:

OBJECTS := \
	$(OBJDIR)/Application.o \
	$(OBJDIR)/Connection.o \
	$(OBJDIR)/ConnectionManager.o \
	$(OBJDIR)/DBAccount.o \
	$(OBJDIR)/DBAccountBan.o \
	$(OBJDIR)/DBAccountItemList.o \
	$(OBJDIR)/DBAccountKey.o \
	$(OBJDIR)/DBAccountKeyAccounts.o \
	$(OBJDIR)/DBAccountKeyList.o \
	$(OBJDIR)/DBAccountList.o \
	$(OBJDIR)/DBAttribute.o \
	$(OBJDIR)/DBAttributeList.o \
	$(OBJDIR)/DBBan.o \
	$(OBJDIR)/DBCharacter.o \
	$(OBJDIR)/DBCharacterList.o \
	$(OBJDIR)/DBConcreteItem.o \
	$(OBJDIR)/DBEffect.o \
	$(OBJDIR)/DBEffectList.o \
	$(OBJDIR)/DBFriendList.o \
	$(OBJDIR)/DBGame.o \
	$(OBJDIR)/DBGameList.o \
	$(OBJDIR)/DBGuild.o \
	$(OBJDIR)/DBGuildMembers.o \
	$(OBJDIR)/DBIpBan.o \
	$(OBJDIR)/DBItem.o \
	$(OBJDIR)/DBItemChanceList.o \
	$(OBJDIR)/DBItemList.o \
	$(OBJDIR)/DBMail.o \
	$(OBJDIR)/DBMailList.o \
	$(OBJDIR)/DBMusic.o \
	$(OBJDIR)/DBMusicList.o \
	$(OBJDIR)/DBPlayerItemList.o \
	$(OBJDIR)/DBProfession.o \
	$(OBJDIR)/DBProfessionList.o \
	$(OBJDIR)/DBReservedName.o \
	$(OBJDIR)/DBService.o \
	$(OBJDIR)/DBServicelList.o \
	$(OBJDIR)/DBSkill.o \
	$(OBJDIR)/DBSkillList.o \
	$(OBJDIR)/DBTypedItemList.o \
	$(OBJDIR)/DBVersion.o \
	$(OBJDIR)/DBVersionList.o \
	$(OBJDIR)/OldestInsertionEviction.o \
	$(OBJDIR)/Server.o \
	$(OBJDIR)/StorageProvider.o \
	$(OBJDIR)/main.o \
	$(OBJDIR)/stdafx.o \

RESOURCES := \

CUSTOMFILES := \

$(TARGET): ${CUSTOMFILES} $(OBJECTS) $(LDDEPS) $(RESOURCES) | $(TARGETDIR)
	@echo Linking abdata
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(CUSTOMFILES): | $(OBJDIR)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
	$(SILENT) mkdir -p $(TARGETDIR)

$(OBJDIR):
	@echo Creating $(OBJDIR)
	$(SILENT) mkdir -p $(OBJDIR)

clean:
	@echo Cleaning abdata
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

$(OBJECTS): | $(OBJDIR)

$(OBJDIR)/Application.o: ../abdata/abdata/Application.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/Connection.o: ../abdata/abdata/Connection.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/ConnectionManager.o: ../abdata/abdata/ConnectionManager.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBAccount.o: ../abdata/abdata/DBAccount.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBAccountBan.o: ../abdata/abdata/DBAccountBan.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBAccountItemList.o: ../abdata/abdata/DBAccountItemList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBAccountKey.o: ../abdata/abdata/DBAccountKey.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBAccountKeyAccounts.o: ../abdata/abdata/DBAccountKeyAccounts.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBAccountKeyList.o: ../abdata/abdata/DBAccountKeyList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBAccountList.o: ../abdata/abdata/DBAccountList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"	
$(OBJDIR)/DBAttribute.o: ../abdata/abdata/DBAttribute.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBAttributeList.o: ../abdata/abdata/DBAttributeList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBBan.o: ../abdata/abdata/DBBan.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBCharacter.o: ../abdata/abdata/DBCharacter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBCharacterList.o: ../abdata/abdata/DBCharacterList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBConcreteItem.o: ../abdata/abdata/DBConcreteItem.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"	
$(OBJDIR)/DBEffect.o: ../abdata/abdata/DBEffect.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBEffectList.o: ../abdata/abdata/DBEffectList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBFriendList.o: ../abdata/abdata/DBFriendList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBGame.o: ../abdata/abdata/DBGame.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBGameList.o: ../abdata/abdata/DBGameList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBGuild.o: ../abdata/abdata/DBGuild.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBGuildMembers.o: ../abdata/abdata/DBGuildMembers.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBIpBan.o: ../abdata/abdata/DBIpBan.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBItem.o: ../abdata/abdata/DBItem.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBItemChanceList.o: ../abdata/abdata/DBItemChanceList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"	
$(OBJDIR)/DBItemList.o: ../abdata/abdata/DBItemList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBMail.o: ../abdata/abdata/DBMail.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBMailList.o: ../abdata/abdata/DBMailList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBMusic.o: ../abdata/abdata/DBMusic.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBMusicList.o: ../abdata/abdata/DBMusicList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBPlayerItemList.o: ../abdata/abdata/DBPlayerItemList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"	
$(OBJDIR)/DBProfession.o: ../abdata/abdata/DBProfession.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBProfessionList.o: ../abdata/abdata/DBProfessionList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBReservedName.o: ../abdata/abdata/DBReservedName.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBService.o: ../abdata/abdata/DBService.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBServicelList.o: ../abdata/abdata/DBServicelList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBSkill.o: ../abdata/abdata/DBSkill.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBSkillList.o: ../abdata/abdata/DBSkillList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBTypedItemList.o: ../abdata/abdata/DBTypedItemList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"	
$(OBJDIR)/DBVersion.o: ../abdata/abdata/DBVersion.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/DBVersionList.o: ../abdata/abdata/DBVersionList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/OldestInsertionEviction.o: ../abdata/abdata/OldestInsertionEviction.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/Server.o: ../abdata/abdata/Server.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/StorageProvider.o: ../abdata/abdata/StorageProvider.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/main.o: ../abdata/abdata/main.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
$(OBJDIR)/stdafx.o: ../abdata/abdata/stdafx.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -c "$<"
