# GNU Make workspace makefile autogenerated by Premake

PROJECTS := abcrypto lua sqlite3 pugixml recast detour

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

abcrypto:
	@echo "==== Building abcrypto ===="
	@${MAKE} --no-print-directory -C . -f abcrypto.make

lua:
	@echo "==== Building lua ===="
	@${MAKE} --no-print-directory -C . -f lua.make

sqlite3:
	@echo "==== Building sqlite3 ===="
	@${MAKE} --no-print-directory -C . -f sqlite3.make

pugixml:
	@echo "==== Building pugixml ===="
	@${MAKE} --no-print-directory -C . -f pugixml.make

recast:
	@echo "==== Building recast ===="
	@${MAKE} --no-print-directory -C . -f recast.make

detour:
	@echo "==== Building detour ===="
	@${MAKE} --no-print-directory -C . -f detour.make

clean:
	@${MAKE} --no-print-directory -C . -f abcrypto.make clean
	@${MAKE} --no-print-directory -C . -f lua.make clean
	@${MAKE} --no-print-directory -C . -f sqlite3.make clean
	@${MAKE} --no-print-directory -C . -f pugixml.make clean
	@${MAKE} --no-print-directory -C . -f recast.make clean
	@${MAKE} --no-print-directory -C . -f detour.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   abcrypto"
	@echo "   lua"
	@echo "   sqlite3"
	@echo "   pugixml"
	@echo "   recast"
	@echo "   detour"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"