.PHONY: clean all

all:
	@$(MAKE) -f  abcrypto.make
	@$(MAKE) -f  pugixml.make
	@$(MAKE) -f  recast.make
	@$(MAKE) -f  detour.make
	@$(MAKE) -f  libless.make
	@$(MAKE) -f  abdb.make
	@$(MAKE) -f  abscommon.make
	@$(MAKE) -f  absmath.make
	@$(MAKE) -f  abdata.make
	@$(MAKE) -f  abfile.make
	@$(MAKE) -f  ablb.make
	@$(MAKE) -f  ablogin.make
	@$(MAKE) -f  abmsgs.make
	@$(MAKE) -f  absadmin.make
	@$(MAKE) -f  abserv.make
	@$(MAKE) -f  abstests.make

clean:
	@$(MAKE) -f  abcrypto.make clean
	@$(MAKE) -f  pugixml.make clean
	@$(MAKE) -f  recast.make clean
	@$(MAKE) -f  detour.make clean
	@$(MAKE) -f  libless.make clean
	@$(MAKE) -f  abdb.make clean
	@$(MAKE) -f  abscommon.make clean
	@$(MAKE) -f  absmath.make clean
	@$(MAKE) -f  abdata.make clean
	@$(MAKE) -f  abfile.make clean
	@$(MAKE) -f  ablb.make clean
	@$(MAKE) -f  ablogin.make clean
	@$(MAKE) -f  abmsgs.make clean
	@$(MAKE) -f  absadmin.make clean
	@$(MAKE) -f  abserv.make clean
	@$(MAKE) -f  abstests.make clean
