.PHONY: clean all

all:
	@"$(MAKE)" -f  "../makefiles/abscommon.make"
	@"$(MAKE)" -f  "../makefiles/ablogin.make"
clean:
	@"$(MAKE)" -f  "../makefiles/abcommon.make" clean
	@"$(MAKE)" -f  "../makefiles/ablogin.make" clean

