.PHONY: clean all

all:
	@"$(MAKE)" -f  "../makefiles/abscommon.make"
	@"$(MAKE)" -f  "../makefiles/abfile.make"
clean:
	@"$(MAKE)" -f  "../makefiles/abscommon.make" clean
	@"$(MAKE)" -f  "../makefiles/abfile.make" clean

