parameters:
  # defaults, if not specified
  configuration: 'Release'

steps:
  - script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=${{ parameters.configuration }} .. && make && ctest --verbose
