.PHONY: clean all

all:
	@"$(MAKE)" -f  "../makefiles/abscommon.make"
	@"$(MAKE)" -f  "../makefiles/abdb.make"
	@"$(MAKE)" -f  "../makefiles/abdata.make"
clean:
	@"$(MAKE)" -f  "../makefiles/abcommon.make" clean
	@"$(MAKE)" -f  "../makefiles/abdb.make" clean
	@"$(MAKE)" -f  "../makefiles/abdata.make" clean

